import { useState,useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home() {

  const [unusedNumber, setUnusedNumber] = useState("")
  const [numberObject, setNumberObject] = useState("")

  

  const fetchData = async () => {
 
    const response = await axios.get("http://localhost:5001/phonegenerator-3ba72/us-central1/app/api/get-phoneNumber")

    const data = await response?.data?.data

    console.log(data)

    if (data === null ||  data === undefined) {
      console.log(data)
 
  return
    }
    console.log("Helooo")
         const newdata = Object?.values(data)
       setUnusedNumber(newdata[0].phoneNumber)
        setNumberObject(data)

    return

  }


  const addNonworkingNumber = async (event) => {

    event.preventDefault()
      console.log(unusedNumber)
     console.log(numberObject)
    await axios.post("http://localhost:5001/phonegenerator-3ba72/us-central1/app/api/add-NonWorkingNumber", numberObject)
    setUnusedNumber('')
    setNumberObject('')
  }

  const getUnusedNumber = (event) => {
   
    event.preventDefault()
    fetchData()

  }


  
  const addWorkingNumber = async (event) => {

    event.preventDefault()
    console.log(unusedNumber)
     console.log(numberObject)
    await axios.post("http://localhost:5001/phonegenerator-3ba72/us-central1/app/api/add-WorkingNumber", numberObject)
    setUnusedNumber("")
     setNumberObject('')
  }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Phone Number Generator</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>

      <main className={styles.main}>
        <div>
       <h1 className={styles.title}>
         Phone Number Generator
        </h1>
        </div>
       
        <button  onClick={getUnusedNumber} className={styles.gbutton} type='submit' >
          Generate Phone Number
        </button>
        <div className={styles.sbutton}>
        {unusedNumber}
        </div>
        <div className={styles.bottom}>
 <h3>Did the Phone Number Exist</h3>
          <div  onClick={addNonworkingNumber} className={styles.check}>
  <Image src="/cross.svg" alt="cross" width={50} height={50} />
          </div>
          
        
          <div  onClick={addWorkingNumber}  >
      <Image src="/check.svg" alt="check" width={50} height={50}/>
          </div>
    
        </div>
       
   


      </main>

 
    </div>
  )
}


