import { useState,useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Understand from 'twilio/lib/rest/preview/Understand'

export default function Home() {

const [unusedNumber, setUnusedNumber] = useState("")

  const fetchData = async () => {
 
    const response = await axios.get("http://localhost:5001/phonegenerator-3ba72/us-central1/app/api/get-phoneNumber")

    const data = response?.data?.data

    const newdata = Object.values(data)

setUnusedNumber(newdata[0].phoneNumber)
    return

  }


  const getUnusedNumber = (event) => {
   
    event.preventDefault()
    fetchData()

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Phone Number Generator</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>

      <main className={styles.main}>
        <div>
       <h1 className={styles.title}>
         Phone Number Generator
        </h1>
        </div>
       
        <button  onClick={getUnusedNumber} className={styles.gbutton} type='submit' >
          Generate Phone Number
        </button>
        <div className={styles.sbutton}>
        {unusedNumber}
        </div>
        <div className={styles.bottom}>
 <h3>Did the Phone Number Exist</h3>
          <div className={styles.check}>
  <Image src="/cross.svg" width={50} height={50} />
          </div>
          
        
          <div  >
      <Image src="/check.svg" width={50} height={50}/>
          </div>
    
        </div>
       
   


      </main>

 
    </div>
  )
}


